# Generated by Django 4.2.7 on 2025-10-09 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('vize', 'Vize'), ('final', 'Final'), ('but', 'Bütünleme')], default='vize', max_length=10, verbose_name='Sınav Türü')),
                ('grade', models.CharField(choices=[('AA', 'AA (90-100)'), ('BA', 'BA (85-89)'), ('BB', 'BB (80-84)'), ('CB', 'CB (75-79)'), ('CC', 'CC (70-74)'), ('DC', 'DC (65-69)'), ('DD', 'DD (60-64)'), ('FD', 'FD (50-59)'), ('FF', 'FF (0-49)')], max_length=2, verbose_name='Not')),
                ('score', models.IntegerField(help_text='0-100 arası puan giriniz', verbose_name='Puan (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Ders')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notes', to=settings.AUTH_USER_MODEL, verbose_name='Öğretmen')),
            ],
            options={
                'verbose_name': 'Not',
                'verbose_name_plural': 'Notlar',
                'ordering': ['-created_at'],
                'unique_together': {('course', 'student', 'exam_type')},
            },
        ),
    ]
