# Generated by Django 5.2.7 on 2025-10-06 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='tc_no',
        ),
        migrations.AddField(
            model_name='student',
            name='school_number',
            field=models.CharField(default=223301100, max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4,20}$', 'Okul numarası 4-20 haneli olmalıdır')]),
            preserve_default=False,
        ),
    ]
