# Generated by Django 4.2.7 on 2025-10-09 22:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)], verbose_name='Hafta')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('content_type', models.CharField(choices=[('lecture', 'Ders Notları'), ('presentation', 'Sunum'), ('video', 'Video'), ('document', 'Doküman'), ('other', 'Diğer')], default='document', max_length=20, verbose_name='İçerik Tipi')),
                ('file', models.FileField(blank=True, null=True, upload_to='course_contents/', verbose_name='Dosya')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.course')),
            ],
            options={
                'verbose_name': 'Ders İçeriği',
                'verbose_name_plural': 'Ders İçerikleri',
                'ordering': ['course', 'week_number'],
                'unique_together': {('course', 'week_number', 'title')},
            },
        ),
    ]
