# Generated by Django 4.2.7 on 2025-11-01 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teachers", "0001_initial"),
        ("courses", "0002_coursecontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("assign", "Atama"),
                            ("remove", "Çıkarma"),
                            ("update", "Güncelleme"),
                            ("bulk_assign", "Toplu Atama"),
                            ("bulk_remove", "Toplu Çıkarma"),
                        ],
                        max_length=20,
                        verbose_name="İşlem",
                    ),
                ),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="İşlem Tarihi"
                    ),
                ),
                (
                    "course_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_history",
                        to="courses.coursegroup",
                        verbose_name="Ders Grubu",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İşlemi Yapan",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_history",
                        to="teachers.teacher",
                        verbose_name="Öğretmen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atama Geçmişi",
                "verbose_name_plural": "Atama Geçmişleri",
                "ordering": ["-timestamp"],
            },
        ),
    ]
