# Generated by Django 4.2.7 on 2025-11-03 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0001_initial"),
        ("courses", "0003_assignmenthistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExampleQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(help_text="Soru metni veya açıklaması")),
                (
                    "question_type",
                    models.CharField(
                        choices=[("quiz", "Quiz"), ("solution", "Çözüm Örneği")],
                        default="solution",
                        max_length=20,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="example_questions/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Kayıtlı Öğrencilere Görünür"),
                            ("hidden", "Gizli"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="example_questions",
                        to="courses.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="example_questions",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Örnek Soru",
                "verbose_name_plural": "Örnek Sorular",
                "ordering": ["-created_at"],
            },
        ),
    ]
