# Generated by Django 4.2.7 on 2025-11-04 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_quiz_quizchoice_quizquestion_quizchoice_question_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlagiarismReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("method", models.CharField(default="ngram_jaccard", max_length=50)),
                ("max_similarity", models.FloatField(default=0.0)),
                ("details", models.JSONField(default=dict)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plagiarism_reports",
                        to="courses.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "İntihal Raporu",
                "verbose_name_plural": "İntihal Raporları",
                "ordering": ["-created_at"],
            },
        ),
    ]
