# Generated by Django 4.2.7 on 2025-12-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_plagiarismreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="grade",
            field=models.CharField(
                choices=[
                    ("AA", "AA"),
                    ("BA", "BA"),
                    ("BB", "BB"),
                    ("CB", "CB"),
                    ("CC", "CC"),
                    ("DC", "DC"),
                    ("DD", "DD"),
                    ("FD", "FD"),
                    ("FF", "FF"),
                    ("NA", "Henüz Değerlendirilmedi"),
                ],
                default="NA",
                max_length=2,
            ),
        ),
    ]
