# Generated by Django 4.2.7 on 2025-11-09 23:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('courses', '0006_plagiarismreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kurs Modülü',
                'verbose_name_plural': 'Kurs Modülleri',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF Döküman'), ('quiz', 'Quiz'), ('text', 'Metin İçerik'), ('assignment', 'Opsiyonel Ödev')], max_length=20, verbose_name='İçerik Tipi')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Sıra')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo veya diğer video platformları', null=True, verbose_name='Video URL')),
                ('video_duration', models.PositiveIntegerField(default=0, help_text='Süre (saniye)', verbose_name='Video Süresi')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='lessons/pdfs/', verbose_name='PDF Dosyası')),
                ('text_content', models.TextField(blank=True, verbose_name='Metin İçerik')),
                ('is_assignment_optional', models.BooleanField(default=True, verbose_name='Ödev Opsiyonel mi?')),
                ('assignment_description', models.TextField(blank=True, verbose_name='Ödev Açıklaması')),
                ('assignment_file', models.FileField(blank=True, null=True, upload_to='lessons/assignments/', verbose_name='Ödev Referans Dosyası')),
                ('is_preview', models.BooleanField(default=False, help_text='Kayıt olmadan izlenebilir mi?', verbose_name='Önizleme')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Tamamlanması zorunlu mu?', verbose_name='Zorunlu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.coursemodule')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_links', to='courses.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
                'ordering': ['module', 'order'],
                'unique_together': {('module', 'order')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('university', 'Üniversite Dersi'), ('online', 'Online Kurs')], default='university', max_length=20, verbose_name='Kurs Tipi'),
        ),
        migrations.AddField(
            model_name='course',
            name='estimated_duration_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Tahmini Süre (Saat)'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_self_paced',
            field=models.BooleanField(default=False, help_text='Öğrenci kendi hızında mı ilerleyecek?', verbose_name='Kendi Hızında'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Başlangıç'), ('intermediate', 'Orta'), ('advanced', 'İleri'), ('expert', 'Uzman')], max_length=20, verbose_name='Seviye'),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/', verbose_name='Kurs Görseli'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course'),
        ),
        migrations.CreateModel(
            name='CourseExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_score', models.FloatField(default=70.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Geçme Notu')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Maksimum Deneme')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Süre (Dakika)')),
                ('instructions', models.TextField(blank=True, help_text='Sınav hakkında öğrencilere verilecek talimatlar', verbose_name='Talimatlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_exam', to='courses.course')),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_exam_link', to='courses.quiz')),
            ],
            options={
                'verbose_name': 'Kurs Sınavı',
                'verbose_name_plural': 'Kurs Sınavları',
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('completed', 'Tamamlandı'), ('expired', 'Süresi Dolmuş'), ('cancelled', 'İptal Edildi')], default='active', max_length=20, verbose_name='Durum')),
                ('progress_percentage', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='İlerleme %')),
                ('completed_lessons_count', models.PositiveIntegerField(default=0, verbose_name='Tamamlanan Ders Sayısı')),
                ('total_lessons_count', models.PositiveIntegerField(default=0, verbose_name='Toplam Ders Sayısı')),
                ('is_eligible_for_exam', models.BooleanField(default=False, help_text='Tüm içerik tamamlandı mı?', verbose_name='Sınava Uygun')),
                ('exam_access_date', models.DateTimeField(blank=True, null=True, verbose_name='Sınav Erişim Tarihi')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('certificate_issued', models.BooleanField(default=False, verbose_name='Sertifika Verildi')),
                ('certificate_issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Sertifika Tarihi')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='Son Erişim')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='students.student')),
            ],
            options={
                'verbose_name': 'Kurs Kaydı',
                'verbose_name_plural': 'Kurs Kayıtları',
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=100, unique=True, verbose_name='Sertifika No')),
                ('issue_date', models.DateTimeField(auto_now_add=True, verbose_name='Düzenlenme Tarihi')),
                ('exam_score', models.FloatField(verbose_name='Sınav Puanı')),
                ('completion_date', models.DateTimeField(verbose_name='Tamamlanma Tarihi')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Sertifika PDF')),
                ('verification_url', models.URLField(blank=True, verbose_name='Doğrulama URL')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Geçerli')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='İptal Tarihi')),
                ('revoked_reason', models.TextField(blank=True, verbose_name='İptal Nedeni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='courses.courseenrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.student')),
            ],
            options={
                'verbose_name': 'Sertifika',
                'verbose_name_plural': 'Sertifikalar',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Başlanmadı'), ('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandı')], default='not_started', max_length=20, verbose_name='Durum')),
                ('watched_duration', models.PositiveIntegerField(default=0, help_text='İzlenen süre (saniye)', verbose_name='İzlenen Süre')),
                ('completion_percentage', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tamamlanma Yüzdesi')),
                ('quiz_score', models.FloatField(blank=True, null=True, verbose_name='Quiz Puanı')),
                ('quiz_passed', models.BooleanField(default=False, verbose_name='Quiz Geçildi')),
                ('assignment_submitted', models.BooleanField(default=False, verbose_name='Ödev Gönderildi')),
                ('assignment_file', models.FileField(blank=True, null=True, upload_to='optional_assignments/', verbose_name='Ödev Dosyası')),
                ('assignment_notes', models.TextField(blank=True, verbose_name='Öğrenci Notları')),
                ('assignment_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='Son Erişim')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='courses.courseenrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.lesson')),
                ('quiz_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_progress', to='courses.quizattempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='students.student')),
            ],
            options={
                'verbose_name': 'Ders İlerlemesi',
                'verbose_name_plural': 'Ders İlerlemeleri',
                'ordering': ['-last_accessed'],
                'unique_together': {('student', 'lesson', 'enrollment')},
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='Deneme No')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Puan')),
                ('status', models.CharField(choices=[('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandı'), ('passed', 'Başarılı'), ('failed', 'Başarısız')], default='in_progress', max_length=20, verbose_name='Durum')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='courses.courseenrollment')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.courseexam')),
                ('quiz_attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempt_link', to='courses.quizattempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='students.student')),
            ],
            options={
                'verbose_name': 'Sınav Denemesi',
                'verbose_name_plural': 'Sınav Denemeleri',
                'ordering': ['-started_at'],
                'unique_together': {('enrollment', 'attempt_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='coursemodule',
            unique_together={('course', 'order')},
        ),
    ]
