# Generated by Django 4.2.7 on 2025-11-09 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursemodule_lesson_course_course_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
