# Generated by Django 4.2.7 on 2025-12-14 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0001_initial"),
        ("courses", "0007_add_fd_grade_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursegroup",
            name="academic_term",
            field=models.ForeignKey(
                blank=True,
                help_text="Akademik dönem (örn: 2024-2025 Güz)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="course_groups",
                to="academic.academicterm",
            ),
        ),
        migrations.AlterField(
            model_name="coursegroup",
            name="semester",
            field=models.CharField(
                help_text="Eski dönem formatı - kullanım dışı", max_length=20
            ),
        ),
    ]
