# Generated by Django 4.2.7 on 2025-11-10 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_delete_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plagiarismreport',
            name='submission',
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='submission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='PlagiarismReport',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
