# Generated by Django 4.2.7 on 2025-12-14 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0008_coursegroup_academic_term_alter_coursegroup_semester"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Çoktan Seçmeli"),
                            ("true_false", "Doğru/Yanlış"),
                            ("short_answer", "Kısa Cevap"),
                            ("essay", "Essay"),
                            ("matching", "Eşleştirme"),
                            ("fill_blank", "Boşluk Doldurma"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Kolay"),
                            ("medium", "Orta"),
                            ("hard", "Zor"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="quiz/questions/"
                    ),
                ),
                (
                    "points",
                    models.DecimalField(decimal_places=2, default=1, max_digits=6),
                ),
                ("option_a", models.CharField(blank=True, max_length=500)),
                ("option_b", models.CharField(blank=True, max_length=500)),
                ("option_c", models.CharField(blank=True, max_length=500)),
                ("option_d", models.CharField(blank=True, max_length=500)),
                ("option_e", models.CharField(blank=True, max_length=500)),
                (
                    "correct_answer",
                    models.TextField(help_text="Correct answer or answer key"),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="Explanation of correct answer"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=500
                    ),
                ),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Soru",
                "verbose_name_plural": "Sorular",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "duration_minutes",
                    models.IntegerField(
                        help_text="Duration in minutes (0 for unlimited)"
                    ),
                ),
                ("max_attempts", models.IntegerField(default=1)),
                (
                    "passing_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=60,
                        help_text="Minimum percentage to pass",
                        max_digits=5,
                    ),
                ),
                ("shuffle_questions", models.BooleanField(default=False)),
                ("shuffle_options", models.BooleanField(default=False)),
                ("show_results_immediately", models.BooleanField(default=False)),
                ("allow_review", models.BooleanField(default=True)),
                (
                    "auto_submit",
                    models.BooleanField(
                        default=True, help_text="Auto-submit when time expires"
                    ),
                ),
                ("require_password", models.BooleanField(default=False)),
                ("password", models.CharField(blank=True, max_length=100)),
                (
                    "ip_restriction",
                    models.TextField(
                        blank=True, help_text="Comma-separated IP addresses or ranges"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="courses.coursegroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizler",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Points for this question in this quiz",
                        max_digits=6,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.question"
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quiz.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("quiz", "question")},
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_number", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "Devam Ediyor"),
                            ("submitted", "Teslim Edildi"),
                            ("auto_submitted", "Otomatik Teslim"),
                            ("abandoned", "Terk Edildi"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("time_spent_seconds", models.IntegerField(default=0)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="quiz.quiz",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Denemesi",
                "verbose_name_plural": "Quiz Denemeleri",
                "ordering": ["-started_at"],
                "unique_together": {("quiz", "student", "attempt_number")},
            },
        ),
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False, help_text="Share with other teachers"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_banks",
                        to="courses.coursegroup",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Soru Bankası",
                "verbose_name_plural": "Soru Bankaları",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quiz.questionbank",
            ),
        ),
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField(blank=True)),
                ("selected_option", models.CharField(blank=True, max_length=1)),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                (
                    "points_earned",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("teacher_feedback", models.TextField(blank=True)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quiz.quizattempt",
                    ),
                ),
                (
                    "quiz_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.quizquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Cevabı",
                "verbose_name_plural": "Quiz Cevapları",
                "unique_together": {("attempt", "quiz_question")},
            },
        ),
    ]
