# Generated by Django 4.2.7 on 2025-12-14 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="quizquestion",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="quiz",
            name="random_question_count",
            field=models.IntegerField(
                default=40, help_text="Her öğrenciye seçilecek soru sayısı"
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="random_question_pool_size",
            field=models.IntegerField(
                default=250,
                help_text="Rastgele seçim için soru havuzu boyutu (soru bankasından)",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="use_random_questions",
            field=models.BooleanField(
                default=False, help_text="Her öğrenciye rastgele sorular seç"
            ),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="assigned_to_student",
            field=models.ForeignKey(
                blank=True,
                help_text="If using random questions, which student this question is assigned to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_quiz_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quizquestion",
            unique_together={("quiz", "question", "assigned_to_student")},
        ),
    ]
