# Generated by Django 4.2.7 on 2025-12-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_alter_quizquestion_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="use_best_attempt",
            field=models.BooleanField(
                default=True,
                help_text="En yüksek puanlı denemeyi not olarak kullan (False ise son deneme)",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="max_attempts",
            field=models.IntegerField(
                default=2, help_text="Maksimum giriş hakkı (varsayılan: 2)"
            ),
        ),
    ]
