# Generated by Django 4.2.7 on 2026-01-02 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0003_quiz_use_best_attempt_alter_quiz_max_attempts"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemQuizSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_duration",
                    models.IntegerField(
                        default=60,
                        help_text="Yeni oluşturulan sınavlar için varsayılan süre",
                        verbose_name="Varsayılan Sınav Süresi (dakika)",
                    ),
                ),
                (
                    "default_max_attempts",
                    models.IntegerField(
                        default=1,
                        help_text="Öğrencilerin sınava kaç kez girebileceği",
                        verbose_name="Varsayılan Deneme Sayısı",
                    ),
                ),
                (
                    "default_passing_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Sınavdan geçmek için gereken minimum puan yüzdesi",
                        max_digits=5,
                        verbose_name="Varsayılan Geçme Notu (%)",
                    ),
                ),
                (
                    "auto_submit_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Süre bittiğinde sınavı otomatik olarak teslim et",
                        verbose_name="Otomatik Teslim Etkin",
                    ),
                ),
                (
                    "show_results_immediately",
                    models.BooleanField(
                        default=False,
                        help_text="Sınav bitiminde sonuçları öğrenciye göster",
                        verbose_name="Sonuçları Hemen Göster",
                    ),
                ),
                (
                    "show_correct_answers",
                    models.BooleanField(
                        default=False,
                        help_text="Sınav sonunda doğru cevapları göster",
                        verbose_name="Doğru Cevapları Göster",
                    ),
                ),
                (
                    "allow_review",
                    models.BooleanField(
                        default=True,
                        help_text="Öğrencilerin sınav sonrası cevaplarını incelemesine izin ver",
                        verbose_name="İncelemeye İzin Ver",
                    ),
                ),
                (
                    "require_password",
                    models.BooleanField(
                        default=False,
                        help_text="Sınavlara giriş için şifre iste",
                        verbose_name="Şifre Gerektir",
                    ),
                ),
                (
                    "ip_restriction_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Sınavlara sadece belirli IP adreslerinden erişime izin ver",
                        verbose_name="IP Kısıtlaması Etkin",
                    ),
                ),
                (
                    "prevent_tab_switch",
                    models.BooleanField(
                        default=True,
                        help_text="Öğrenci sınav sırasında başka sekmeye geçerse uyar",
                        verbose_name="Sekme Değiştirmeyi Engelle",
                    ),
                ),
                (
                    "quiz_system_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Tüm sınav sistemini aktif/pasif yap",
                        verbose_name="Sınav Sistemi Aktif",
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Sınav sistemi bakımda (sadece adminler erişebilir)",
                        verbose_name="Bakım Modu",
                    ),
                ),
                (
                    "maintenance_message",
                    models.TextField(
                        blank=True,
                        help_text="Bakım modunda gösterilecek mesaj",
                        verbose_name="Bakım Mesajı",
                    ),
                ),
                (
                    "notify_teacher_on_completion",
                    models.BooleanField(
                        default=True,
                        help_text="Öğrenci sınavı tamamladığında öğretmene email gönder",
                        verbose_name="Öğretmene Bildirim Gönder",
                    ),
                ),
                (
                    "notify_student_on_grade",
                    models.BooleanField(
                        default=True,
                        help_text="Sınav notlandırıldığında öğrenciye bildirim gönder",
                        verbose_name="Öğrenciye Not Bildirimi",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Son Güncellenme"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Güncelleyen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sınav Sistem Ayarları",
                "verbose_name_plural": "Sınav Sistem Ayarları",
            },
        ),
    ]
