# Generated by Django 4.2.7 on 2025-10-16 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('assignment', 'Ödev'), ('announcement', 'Duyuru'), ('grade', 'Not'), ('welcome', 'Hoş Geldin')], max_length=20)),
                ('notification_id', models.CharField(max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirim Durumu',
                'verbose_name_plural': 'Bildirim Durumları',
                'unique_together': {('user', 'notification_id')},
            },
        ),
    ]
