# Generated by Django 4.2.7 on 2025-12-14 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0008_coursegroup_academic_term_alter_coursegroup_semester"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollmentRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("prerequisite", "Ön Koşul"),
                            ("corequisite", "Eş Koşul"),
                            ("department", "Bölüm Kısıtı"),
                            ("year", "Yarıyıl Kısıtı"),
                            ("grade", "Not Kısıtı"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "min_grade",
                    models.CharField(
                        blank=True,
                        help_text="Minimum geçer not (örn: DD)",
                        max_length=2,
                    ),
                ),
                (
                    "allowed_departments",
                    models.TextField(
                        blank=True,
                        help_text="İzin verilen bölümler (virgülle ayrılmış)",
                    ),
                ),
                (
                    "allowed_years",
                    models.CharField(
                        blank=True,
                        help_text="İzin verilen yarıyıllar (örn: 1,2,3)",
                        max_length=50,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Kural ihlalinde gösterilecek özel mesaj"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment_rules",
                        to="courses.coursegroup",
                    ),
                ),
                (
                    "prerequisite_course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisite_for",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kayıt Kuralı",
                "verbose_name_plural": "Kayıt Kuralları",
            },
        ),
        migrations.CreateModel(
            name="EnrollmentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manuel Kayıt"),
                            ("self", "Öğrenci Kayıt"),
                            ("key", "Anahtar ile Kayıt"),
                            ("cohort", "Toplu Kayıt"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Bu kayıt yöntemi aktif mi?"
                    ),
                ),
                (
                    "enrollment_key",
                    models.CharField(
                        blank=True,
                        help_text="Kayıt anahtarı (key tipi için gerekli)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "max_students",
                    models.IntegerField(
                        blank=True,
                        help_text="Maksimum öğrenci sayısı (boş = sınırsız)",
                        null=True,
                    ),
                ),
                (
                    "allow_self_unenroll",
                    models.BooleanField(
                        default=True,
                        help_text="Öğrenci kendi kayıtını iptal edebilir mi?",
                    ),
                ),
                (
                    "enrollment_start",
                    models.DateTimeField(
                        blank=True, help_text="Kayıt başlangıç tarihi", null=True
                    ),
                ),
                (
                    "enrollment_end",
                    models.DateTimeField(
                        blank=True, help_text="Kayıt bitiş tarihi", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment_methods",
                        to="courses.coursegroup",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_enrollment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kayıt Yöntemi",
                "verbose_name_plural": "Kayıt Yöntemleri",
            },
        ),
    ]
