# Generated by Django 5.2.7 on 2025-10-06 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='final_grade',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Final Notu'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='makeup_grade',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Büt Notu'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='midterm_grade',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Vize Notu'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='project_grade',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Proje Notu'),
        ),
    ]
