# Generated by Django 4.2.7 on 2025-12-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Örnek: 2024-2025 Güz", max_length=100, unique=True
                    ),
                ),
                (
                    "year_start",
                    models.IntegerField(help_text="Başlangıç yılı (örn: 2024)"),
                ),
                ("year_end", models.IntegerField(help_text="Bitiş yılı (örn: 2025)")),
                (
                    "term_type",
                    models.CharField(
                        choices=[
                            ("fall", "Güz"),
                            ("spring", "Bahar"),
                            ("summer", "Yaz"),
                        ],
                        help_text="Dönem tipi",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField(help_text="Dönem başlangıç tarihi")),
                ("end_date", models.DateField(help_text="Dönem bitiş tarihi")),
                (
                    "registration_start",
                    models.DateField(
                        blank=True, help_text="Ders kaydı başlangıç tarihi", null=True
                    ),
                ),
                (
                    "registration_end",
                    models.DateField(
                        blank=True, help_text="Ders kaydı bitiş tarihi", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planlandı"),
                            ("active", "Aktif"),
                            ("completed", "Tamamlandı"),
                            ("archived", "Arşivlendi"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Aktif dönem (aynı anda sadece 1 dönem aktif olabilir)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Dönem hakkında notlar"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Akademik Dönem",
                "verbose_name_plural": "Akademik Dönemler",
                "ordering": ["-year_start", "-term_type"],
                "unique_together": {("year_start", "year_end", "term_type")},
            },
        ),
    ]
