# Generated by Django 4.2.7 on 2025-10-09 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_no', models.CharField(max_length=11, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Erkek'), ('F', 'Kadın')], max_length=1)),
                ('title', models.CharField(help_text='Ör: Prof. Dr., Doç. Dr., Dr.', max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('hire_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Pasif'), ('retired', 'Emekli'), ('suspended', 'Askıda')], default='active', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Öğretmen',
                'verbose_name_plural': 'Öğretmenler',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
