# Generated by Django 4.2.7 on 2025-12-14 14:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0008_coursegroup_academic_term_alter_coursegroup_semester"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("exam", "Sınav"),
                            ("quiz", "Quiz"),
                            ("homework", "Ödev"),
                            ("project", "Proje"),
                            ("lab", "Laboratuvar"),
                            ("attendance", "Devam"),
                            ("participation", "Katılım"),
                            ("other", "Diğer"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Yüzdelik ağırlık (toplam 100 olmalı)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_categories",
                        to="courses.coursegroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Not Kategorisi",
                "verbose_name_plural": "Not Kategorileri",
                "ordering": ["-weight", "name"],
                "unique_together": {("course_group", "name")},
            },
        ),
        migrations.CreateModel(
            name="GradeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "weight_in_category",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="Kategori içindeki ağırlık %",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Taslak"),
                            ("published", "Yayınlandı"),
                            ("graded", "Notlandırıldı"),
                            ("archived", "Arşivlendi"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "is_extra_credit",
                    models.BooleanField(
                        default=False, help_text="Ek puan mı? (Ortalamayı yükseltir)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="gradebook.gradecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Not Kalemi",
                "verbose_name_plural": "Not Kalemleri",
                "ordering": ["-due_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_excused",
                    models.BooleanField(
                        default=False, help_text="Mazeret (hesaplamaya katılmaz)"
                    ),
                ),
                ("is_late", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_grades",
                        to="courses.enrollment",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="gradebook.gradeitem",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Not",
                "verbose_name_plural": "Notlar",
                "ordering": ["-graded_at", "-created_at"],
                "unique_together": {("student", "item")},
            },
        ),
    ]
