# Generated by Django 4.2.7 on 2025-10-10 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Oluşturma'), ('update', 'Güncelleme'), ('delete', 'Silme'), ('login', 'Giriş'), ('logout', 'Çıkış'), ('view', 'Görüntüleme'), ('export', 'Dışa Aktarma'), ('enroll', 'Kayıt'), ('submit', 'Teslim'), ('grade', 'Notlandırma')], max_length=20, verbose_name='İşlem')),
                ('model_name', models.CharField(help_text='Etkilenen model adı (örn: Student, Course)', max_length=50, verbose_name='Model Adı')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='Nesne ID')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='Nesne Gösterimi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='Tarayıcı Bilgisi')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zaman')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Aktivite Logu',
                'verbose_name_plural': 'Aktivite Logları',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Alan Adı')),
                ('old_value', models.TextField(blank=True, verbose_name='Eski Değer')),
                ('new_value', models.TextField(blank=True, verbose_name='Yeni Değer')),
                ('activity_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='utils.activitylog', verbose_name='Aktivite Logu')),
            ],
            options={
                'verbose_name': 'Değişiklik Geçmişi',
                'verbose_name_plural': 'Değişiklik Geçmişleri',
            },
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-timestamp'], name='utils_activ_timesta_bdf27d_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-timestamp'], name='utils_activ_user_id_4d6186_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['model_name', '-timestamp'], name='utils_activ_model_n_855c77_idx'),
        ),
    ]
