# Generated by Django 4.2.7 on 2026-01-02 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("content", models.TextField(verbose_name="İçerik")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Düşük"),
                            ("normal", "Normal"),
                            ("high", "Yüksek"),
                            ("urgent", "Acil"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Öncelik",
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all", "Tüm Kullanıcılar"),
                            ("students", "Öğrenciler"),
                            ("teachers", "Öğretmenler"),
                            ("admins", "Adminler"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="Hedef Kitle",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Taslak"),
                            ("active", "Aktif"),
                            ("expired", "Süresi Dolmuş"),
                            ("archived", "Arşivlendi"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        help_text="Duyurunun gösterilmeye başlanacağı tarih",
                        verbose_name="Başlangıç Tarihi",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Duyurunun gösterilmeyi durduracağı tarih (opsiyonel)",
                        null=True,
                        verbose_name="Bitiş Tarihi",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sistem Duyurusu",
                "verbose_name_plural": "Sistem Duyuruları",
                "ordering": ["-priority", "-start_date"],
                "indexes": [
                    models.Index(
                        fields=["-start_date"], name="utils_syste_start_d_715741_idx"
                    ),
                    models.Index(
                        fields=["status", "-start_date"],
                        name="utils_syste_status_6f7a36_idx",
                    ),
                    models.Index(
                        fields=["target_audience", "status"],
                        name="utils_syste_target__2f6b61_idx",
                    ),
                ],
            },
        ),
    ]
